# Generated by Django 3.2.20 on 2023-07-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
